### ISSUE TITLE
Min char count

### ISSUE THREAD

**Issue by nico-martin** [vanderlee/phpSyllable#10]
Hy there

Great project. Thank you!

Is it possible to only hyphenate words with more than X characters?

So with a min length of 10 characters it would be:
"Provide your own paragraphs..." -> "Provide your own pa-ra-graphs..."
 
Kind regards,
Nico

**Comment by vanderlee** [comment]
Currently it's not possible, but it should be pretty easy to implement as counting chars is already part of the algorithm.
I'm quite busy at the moment, but I hope to be able to find some time to implement this next week.
Ofcourse, if you could create a pull request with the fix, that'd be even better ;)

**Comment by vanderlee** [comment]
Fixed issue. New version should be updated in Composer automatically.

**Comment by nico-martin** [comment]
This is great! Thank you!
