### ISSUE TITLE
White-/Blacklist certain HTML Elements in hyphenateHtml()

### ISSUE THREAD

**Issue by Blackskyliner** [vanderlee/phpSyllable#13]
Is it possible to add some kind fo white- and/or blacklist for certain HTML Elements while processing the HTML to hyphenate?

Background: I try yo use this on whole content areas on dynamically generated pages. Those pages may contain `<script>` Elements and the Javascript will then be destroyed by the hyphening proccess in the current non white-/blacklist behaviour.

I could also write an PR for this feature I guess it should be simple as we would only need to modify the recursive HTML Dom Walker.

**Comment by vanderlee** [comment]
Hi, Thanks for the many PR's submitted. I'm a bit short on time, but will try to get to them next sunday at the latest. FWIW, they all seem okay initially, but I want to take a closer look at the whitelist/blacklist solution. If at all possible, I'd like to extend on the idea so you can include/exclude based on attributes and other structural elements as well. Perhaps an xpath- and/or callback-based solution. Preferably something that can be set on the class instead (or in addition to) the method, so it can be configured inside frameworks.

**Comment by Blackskyliner** [comment]
Feature included with  6b65cf9
