### ISSUE TITLE
Error when trying to use the functions

### ISSUE THREAD

**Issue by Vicedivic** [vanderlee/phpSyllable#27]
Hi Van der Lee,

I really appreciate your project, well done!
There's just one problem: whenever I try to use one of the functions of the class Syllable, it gives me this error:
Warning: file_put_contents(/Users/victor/Sites/pyglatin/phpSyllable-master/classes/../cache/syllable.en-us.json): failed to open stream: No such file or directory in /Users/victor/Sites/pyglatin/phpSyllable-master/classes/Syllable_Cache_FileAbstract.php on line 43

**Comment by Vicedivic** [comment]
UPDATE: I found out what was the problem 👍

**Comment by hshahdoost** [comment]
I'm facing a similar problem, could you please tell the solution
