### ISSUE TITLE
Uppercase words

### ISSUE THREAD

**Issue by jarilehtinen** [vanderlee/phpSyllable#3]
It seems that phpSyllable can hyphenate Finnish word "kolmivaihekilowattituntimittari" very well, but fails (returns the whole word) if written in uppercase letters ("KOLMIVAIHEKILOWATTITUNTIMITTARI").

I'm using:

`$syllable->setTreshold(Syllable::TRESHOLD_MOST);`

Ideas?

**Comment by vanderlee** [comment]
Turns out it was a bug; it was case sensitive and happened in all languages.
Was an easy fix though; now in the repository.
