### ISSUE TITLE
no autoloader for PHP 7+ 

### ISSUE THREAD

**Issue by rob-lindman** [vanderlee/phpSyllable#34]
is there a single include file that can be used to load all of the classes?

**Comment by alexander-nitsche** [comment]
Sure, by using default Composer PSR-4 autoloading via
```
composer require vanderlee/syllable
```
at the CLI and loading the single, automatically generated class mappings file via
```
require __DIR__ . '/vendor/autoload.php';
```
in your project's root file. See https://getcomposer.org/doc/01-basic-usage.md#autoloading.
