### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by rinart73** [vanderlee/phpSyllable#40]
PHP 7.4. I installed the composer version of the library.
I'm getting the "Array and string offset access syntax with curly braces is deprecated" warning for `/vanderlee/syllable/classes/Syllable.php:483`

**Comment by alexander-nitsche** [comment]
Should have been solved in meantime with this [commit](https://github.com/vanderlee/phpSyllable/commit/e0d1424fc559fa61e7791d415d2b2752d8904e38).

**Comment by alexander-nitsche** [comment]
Fixed.
