### ISSUE TITLE
Results differ from syllable.toyls.com

### ISSUE THREAD

**Issue by khaxan** [vanderlee/phpSyllable#41]
Hi, thanks for this library.

I assume that the website https://syllable.toyls.com/ uses the same library underneath? If so I'm not sure why I am getting different (incorrect) results on my end whereas correct results on the website.

I am using the following string:

> Muchos años después, frente al pelotón de fusilamiento, el coronel Aureliano Buendía había de recordar aquella tarde remota en que su padre lo llevó a conocer el hielo. Macondo era entonces una aldea de veinte casas de barro y cañabrava construidas a la orilla de un río de aguas diáfanas que se precipitaban por un lecho de piedras pulidas, blancas y enormes como huevos prehistóricos. El mundo era tan reciente, que muchas cosas carecían de nombre, y para mencionarlas había que señalarlas con el dedo. Todos los años, por el mes de marzo, una familia de gitanos desarrapados plantaba su carpa cerca de la aldea, y con un grande alboroto de pitos y timbales daban a conocer los nuevos inventos. Primero llevaron el imán. Un gitano corpulento, de barba montaraz y manos de gorrión, que se presentó con el nombre de Melquíades, hizo una truculenta demostración pública de lo que él mismo llamaba la octava maravilla de los sabios alquimistas de Macedonia.

In code I am getting this result:

> Mu-chos años de-s-pués, fre-n-te al pe-lo-tón de fu-si-la-mie-n-to, el co-ro-nel Au-re-liano Bue-n-día ha-bía de re-co-r-dar aque-lla ta-r-de re-mo-ta en que su pa-dre lo lle-vó a co-no-cer el hie-lo. Ma-co-n-do era en-to-n-ces una al-dea de vei-n-te ca-sas de ba-rro y ca-ña-bra-va co-n-s-trui-das a la ori-lla de un río de aguas diá-fa-nas que se pre-ci-pi-ta-ban por un le-cho de pie-dras pu-li-das, bla-n-cas y eno-r-mes co-mo hue-vos pre-hi-s-tó-ri-cos. El mu-n-do era tan re-cie-n-te, que mu-chas co-sas ca-re-cían de no-m-bre, y pa-ra me-n-cio-nar-las ha-bía que se-ña-lar-las con el de-do. To-dos los años, por el mes de ma-r-zo, una fa-mi-lia de gi-ta-nos des-arra-pa-dos pla-n-ta-ba su ca-r-pa ce-r-ca de la al-dea, y con un gra-n-de al-bo-ro-to de pi-tos y ti-m-ba-les da-ban a co-no-cer los nue-vos in-ve-n-tos. Pri-me-ro lle-va-ron el imán. Un gi-tano co-r-pu-le-n-to, de ba-r-ba mo-n-ta-raz y ma-nos de go-rrión, que se pre-se-n-tó con el no-m-bre de Me-l-quía-des, hi-zo una tru-cu-le-n-ta de-mo-s-tra-ción pú-bli-ca de lo que él mi-s-mo lla-ma-ba la oc-ta-va ma-ra-vi-lla de los sa-bios al-qui-mi-s-tas de Ma-ce-do-nia.

Whereas on the website I am getting:

> Mu-chos años des-pués, fren-te al pe-lo-tón de fu-si-la-mien-to, el co-ro-nel Au-re-liano Buen-día ha-bía de re-cor-dar aque-lla tar-de re-mo-ta en que su pa-dre lo lle-vó a co-no-cer el hie-lo. Ma-con-do era en-ton-ces una al-dea de vein-te ca-sas de ba-rro y ca-ña-bra-va cons-trui-das a la ori-lla de un río de aguas diá-fa-nas que se pre-ci-pi-ta-ban por un le-cho de pie-dras pu-li-das, blan-cas y enor-mes co-mo hue-vos prehis-tó-ri-cos. El mun-do era tan re-cien-te, que mu-chas co-sas ca-re-cían de nom-bre, y pa-ra men-cio-nar-las ha-bía que se-ña-lar-las con el de-do. To-dos los años, por el mes de mar-zo, una fa-mi-lia de gi-ta-nos desarra-pa-dos plan-ta-ba su car-pa cer-ca de la al-dea, y con un gran-de al-bo-ro-to de pi-tos y tim-ba-les da-ban a co-no-cer los nue-vos in-ven-tos. Pri-me-ro lle-va-ron el imán. Un gi-tano cor-pu-len-to, de bar-ba mon-ta-raz y ma-nos de go-rrión, que se pre-sen-tó con el nom-bre de Mel-quía-des, hi-zo una tru-cu-len-ta de-mos-tra-ción pú-bli-ca de lo que él mis-mo lla-ma-ba la oc-ta-va ma-ra-vi-lla de los sa-bios al-qui-mis-tas de Ma-ce-do-nia.

Notice that in code the hyphenation "Ma-co-n-do" and "Bue-n-día" are incorrect whereas on the website they are correct.

Could you help? Am I doing something wrong on my end that's causing incorrect hyphenation?

I am simply doing:

(new Syllable( 'es', '-' ))->hyphenateText($string);

**Comment by vanderlee** [comment]
Hi,

Thanks for the notice. I'm aware of the issue. Basically, the site isn't
yet using the latest version of phpSyllable. I guess I just kinda forgot
about it :).

Regardless, the way it's all constructed means the github-hosted
phpSyllable will always be the most recent version.

As for the difference, it might have something to do with character
encoding used. You could try converting the text to ascii to see if this is
the case. Otherwise please raise a ticket on github. I'm not very active
recently, but that's the only way these things won't get lost.

Kind regards,
Martijn

Op za 19 mrt. 2022 om 22:19 schreef khaxan ***@***.***>:
