### ISSUE TITLE
Update language files

### ISSUE THREAD

**Issue by alexander-nitsche** [vanderlee/phpSyllable#44]
Hi @vanderlee ,

I was wondering if there is _the_ way to update the language files, for example the German language file [/languages/hyph-de-1996.tex](https://github.com/vanderlee/phpSyllable/blob/master/languages/hyph-de-1996.tex) was last updated in 2016 and there is a 2021 version in its original location http://mirror.ctan.org/language/hyph-utf8/tex/generic/hyph-utf8/patterns/tex/hyph-de-1996.tex.

If this work was previously done by hand and you think a script might be helpful to update language files at the push of a button, I would be happy to provide one.

Thanks for this great package!
Alex

**Comment by vanderlee** [comment]
I notice new updates coming in regularly. Are the PR's ready to merge?

**Comment by alexander-nitsche** [comment]
> I notice new updates coming in regularly.
Yes. I would close this PR in favor of only merging PR #45 , which will automatically fetch these language files on a monthly basis, starting with April 1st.

**Comment by alexander-nitsche** [comment]
Done.
