### ISSUE TITLE
Replace test execution by Travis CI with GitHub Action

### ISSUE THREAD

**Issue by alexander-nitsche** [vanderlee/phpSyllable#48]
Travis CI has more or less limited its service to paying customers and withdrawn from activities in open source communities.

The current Travis configuration let's GitHub checks fail with 
```
continuous-integration/travis-ci Expected — Waiting for status to be reported
```

**Comment by vanderlee** [comment]
Travis CI should be removed from our configuration. Should be replaced with a different CI system if possible.
