### ISSUE TITLE
Allow auto merge for this repository

### ISSUE THREAD

**Issue by alexander-nitsche** [vanderlee/phpSyllable#54]
Hi Martijn,

for the automatic update of languages to work, this repository must be allowed to automatically merge PRs. It is explained [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository) and can only be allowed by the administrator. Currently the "Update languages" workflow fails with "Pull request - Auto merge is not allowed for this repository".

Greetings
Alex

**Comment by vanderlee** [comment]
Auto merge is enabled.
