### ISSUE TITLE
Request for feedback; deprecated splitWord

### ISSUE THREAD

**Issue by vanderlee** [vanderlee/phpSyllable#57]
Looking into the data `splitWord` method in Syllable appears to be somewhat useless; it produces incorrect results at times.

When provided with the same single-word input with random punctuation, `splitText` produces the results expected for `splitWord`.

Propose to mark `splitWord` as deprecated and route to `splitText` internally.

Similarly, the proposed `splitWords` would be better based on `splitText`.

**Comment by alexander-nitsche** [comment]
`splitWord` is probably faster than `splitText` if used for a single word. Would keep it.

**Comment by alexander-nitsche** [comment]
Can this issue be closed?

**Comment by vanderlee** [comment]
Agreed
