### ISSUE TITLE
lowercase vs uppercase hyphenation word list

### ISSUE THREAD

**Issue by mtox** [vanderlee/phpSyllable#70]
Using the word list \hyphenation{...} in language files works only with words in upper or lower case, but not generalized (e.g. gegenstand does not match with Gegenstand). Maybe the script could just basically match in lowercase the hyphenation{..} word list?

Example: add some custom words in a language-file in a section
\hyphenation{
German
}
to define that "German" should not be splitted.

So only "German" is matched and not split, but "german" is split by regular rules of the language file. Thus, redundant rules for "german" and "German" have to be inserted in language files in the end.

**Comment by mtox** [comment]
simple solution: in Syllable.php -> function parseWord -> starting Line 689 you can replace by

```
// Is it a pre-hyphenated word?
if (isset($this->hyphenation[mb_strtolower($word)])) {
	$rule_chars = mb_str_split($this->hyphenation[mb_strtolower($word)]); // Split the rules string into an array of characters

	$output = '';
	$pos = 0;
        //loop through the chars and apply rules defined by the hyphen - 
	foreach ($rule_chars as $char) {
	  if ($char == '-') {
		$output .= '-';
	  } else {
		$output .= mb_substr($word, $pos, 1);
		$pos++;
	  }
	}
	return mb_split('-',$output);
}
```
in language-file (e.g. hyph-de.tex) you simply need to define rules for syllables in lowercase
```
\hypenation{
german
}
```

**Comment by alexander-nitsche** [comment]
I think this is a valid request because the patterns (given by command `\patterns`) are used case-insensitive too.
