### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by alexander-nitsche** [vanderlee/phpSyllable#75]
Hi @vanderlee ,

these branches might be ready for deletion as they are already merged or outdated:

- https://github.com/vanderlee/phpSyllable/tree/language-update-2023-04-01-09-56-43 (merged)
- https://github.com/vanderlee/phpSyllable/tree/language-update-2023-04-01-01-04-49 (merged)
- https://github.com/vanderlee/phpSyllable/tree/Remove-Travis-badge (merged)
- https://github.com/vanderlee/phpSyllable/tree/Remove-TravisCI-configuration (merged)
- https://github.com/vanderlee/phpSyllable/tree/refactor-php72 (oudated?)
- https://github.com/vanderlee/phpSyllable/tree/refactor (merged)
- https://github.com/vanderlee/phpSyllable/tree/patch/readme-buildstate (merged)
- https://github.com/vanderlee/phpSyllable/tree/gh-pages (merged)

and these issues might be ready for closing as they are addressed in the current master branch:

- #32 
- #28

and this pull request might be ready for closing as it is also addressed in the current master branch:

- #23 

Greetings
Alex

**Comment by vanderlee** [comment]
`gh-pages` is used to host the GItHub pages. It should probably be updated to match master but should not be deleted. The rest can go
