### ISSUE TITLE
German umlauts broken after using ->hyphenateHtml

### ISSUE THREAD

**Issue by Suranex** [vanderlee/phpSyllable#9]
I'm trying to use phpSyllable, but have a problem with the German umlauts.

My example 
`
$html = 'Dies ist ein <a href="http://example.com" target="_blank">Text</a> mit <b>Deutschen</b> umlauten. ä ö ü ß';
$syllable = new Syllable('de');
echo $syllable->hyphenateHtml($html);
`

results in 

`<p>Dies ist ein <a href="http://example.com" target="_blank">Text</a> mit <b>Deut&shy;schen</b> um&shy;lau&shy;ten. Ã¤ Ã¶ Ã¼ ÃŸ</p>` 

Maybe you can help me?

My Environment:
Ubuntu with Apache 2.4 and PHP 5.6.23

**Comment by jacobmellin** [comment]
The algorithm doesn't seem to handle utf8. This does the trick for me:

```
utf8_encode($syllable->hyphenateHtml(utf8_decode($text)))
```

**Comment by zavagli** [comment]
This work fine for me  

$syllable->hyphenateHtml( utf8_decode( " <span>üuuu ö ä</span> " ) );
